//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.18
//
//

import AWSCore


// Name of SafetyAssistantBot bot
let SafetyAssistantBotBotName = "SafetyAssistantBot"
// Alias for SafetyAssistantBot bot
let SafetyAssistantBotBotAlias = "SafetyAssistant"
// Region for SafetyAssistantBot bot
let SafetyAssistantBotBotRegion: AWSRegionType = .USEast1

let CognitoIdentityPoolId = "us-east-1:ff119631-b8e0-432d-9f5f-c8d3abc221ca"
